services:
  db:
    image: postgres:16
    container_name: textRpg-db
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: textRpg
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
